export const images = {
  // Login
  vi: require('assets/images/vi.svg').default,
  en: require('assets/images/en.svg').default,
  logo: require('assets/images/logo.svg').default,
  facebook: require('assets/images/facebook.svg').default,
  google: require('assets/images/google.svg').default,
  apple: require('assets/images/apple.svg').default,
  bgLogin: require('assets/images/bgLogin.svg').default,
  bgLoginMobile: require('assets/images/bgLoginMobile.svg').default,
  bgLoginTop: require('assets/images/bgLoginTop.svg').default,
  bgLoginTopMobile: require('assets/images/bgLoginTopMobile.svg').default,
  bgLoginBotMobile: require('assets/images/bgLoginBotMobile.svg').default,
  bgPopUp: require('assets/images/bgPopUp.svg').default,
  warn: require('assets/images/warn.svg').default,
  success: require('assets/images/success.svg').default,

  // Profile
  nicknamePro: require('assets/images/nicknamePro.svg').default,
  modePro: require('assets/images/modePro.svg').default,
  birthPro: require('assets/images/birthPro.svg').default,
  birthProMobile: require('assets/images/birthProMobile.svg').default,
  descPro: require('assets/images/descPro.svg').default,
  genderPro: require('assets/images/genderPro.svg').default,
  illustrating: require('assets/images/illustrating.svg').default,
  tips: require('assets/images/tips.svg').default,

  // Zodiac
  LibraZ: require('assets/images/CreateZodiac/LibraZ.svg').default,
  AquariusZ: require('assets/images/CreateZodiac/AquariusZ.svg').default,
  AriesZ: require('assets/images/CreateZodiac/AriesZ.svg').default,
  CancerZ: require('assets/images/CreateZodiac/CanerZ.svg').default,
  CapricornZ: require('assets/images/CreateZodiac/CapricornZ.svg').default,
  GeminiZ: require('assets/images/CreateZodiac/GeminiZ.svg').default,
  LeoZ: require('assets/images/CreateZodiac/LeoZ.svg').default,
  PiscesZ: require('assets/images/CreateZodiac/PiscesZ.svg').default,
  SagittariusZ: require('assets/images/CreateZodiac/SagittariusZ.svg').default,
  ScorpionZ: require('assets/images/CreateZodiac/ScorpionZ.svg').default,
  VirgoZ: require('assets/images/CreateZodiac/VirgoZ.svg').default,
  TaurusZ: require('assets/images/CreateZodiac/TaurusZ.svg').default,

  LibraE: require('assets/images/EditZodiac/Libra.svg').default,
  AquariusE: require('assets/images/EditZodiac/Aquarius.svg').default,
  AriesE: require('assets/images/EditZodiac/Aries.svg').default,
  CancerE: require('assets/images/EditZodiac/Cancer.svg').default,
  CapricornE: require('assets/images/EditZodiac/Capricorn.svg').default,
  GeminiE: require('assets/images/EditZodiac/Gemini.svg').default,
  LeoE: require('assets/images/EditZodiac/Leo.svg').default,
  PiscesE: require('assets/images/EditZodiac/Pisces.svg').default,
  SagittariusE: require('assets/images/EditZodiac/Sagittarius.svg').default,
  ScorpionE: require('assets/images/EditZodiac/Scorpion.svg').default,
  VirgoE: require('assets/images/EditZodiac/Virgo.svg').default,
  TaurusE: require('assets/images/EditZodiac/Taurus.svg').default,

  // Home
  noYet: require('assets/images/noYet.svg').default,
  messBox: require('assets/images/messBox.svg').default,
  messBoxRight: require('assets/images/messBoxRight.svg').default,
  noConver: require('assets/images/noConver.png'),

  // About
  diaBlue: require('assets/images/About/diaBlue.svg').default,
  diaYellow: require('assets/images/About/diamond.svg').default,
  logout: require('assets/images/About/logout.svg').default,

  // Favorite
  Billiards: require('assets/images/Favorite/Billards.svg').default,
  Bookstores: require('assets/images/Favorite/Bookstores.svg').default,
  Bowlings: require('assets/images/Favorite/Bowlings.svg').default,
  Cafe: require('assets/images/Favorite/Cafe.svg').default,
  Karaoke: require('assets/images/Favorite/Karaoke.svg').default,
  Lounge: require('assets/images/Favorite/Lounge.svg').default,
  Malls: require('assets/images/Favorite/Malls.svg').default,
  Movies: require('assets/images/Favorite/Movies.svg').default,
  Picnic: require('assets/images/Favorite/Picnic.svg').default,
  Restaurant: require('assets/images/Favorite/Restaurant.svg').default,
  StreetFood: require('assets/images/Favorite/StreetFood.svg').default,
  WalkingStreet: require('assets/images/Favorite/WalkingStreet.svg').default,
  BarsBub: require('assets/images/Favorite/BarsBub.svg').default,
};
